
<ul class="nav nav-tabs" >
    <li class="nav-item">
        <a class="nav-link" href="/products" style="-webkit-text-fill-color: black;">Продукты</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="/orders" style="-webkit-text-fill-color: black;">Поставки</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="/stocks" style="-webkit-text-fill-color: black;">Запас</a>
    </li>

</ul>

